name: clients
port: 30003
deployment:
  replicas: 3
  env:
    BOOK_SERVICE: "books"

public:
  - path: "/ping"
    method: "GET"
    id: "GET_PING"

  - path: "/health"
    method: "GET"
    id: "GET_HEALTH"
